version: '3'

services:
    wordpress:
        image: wordpress
        container_name: wordpress
        restart: always
        volumes:
            - ./wp-content:/var/www/html/wp-content
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_NAME: marketingvideos-dashboard
            WORDPRESS_DB_USER: root
            WORDPRESS_DB_PASSWORD: 12345678
        ports:
            - 8080:80
            - 443:443

    db:
        image: mysql:8
        container_name: mysql
        restart: always
        command: "--default-authentication-plugin=mysql_native_password"
        environment:
            MYSQL_ROOT_PASSWORD: 12345678
            MYSQL_DATABASE: marketingvideos-dashboard
            MYSQL_USER: root
            MYSQL_PASSWORD: 12345678

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - 3333:80
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORT: 12345678